# Fix for Issue #2609: [$100 Bounty] Parallax Occlusion Mapping
# Auto-generated by bounty-executor v19

// ParallaxOcclusionMapping.hx
package armory.graphics.shaders;

import armory.graphics.GL;
import armory.graphics.Shader;

class ParallaxOcclusionMapping {
    public var scale:Float;
    public var bias:Float;
    public var samples:Int;
    public var shader:Shader;

    public function new(scale:Float, bias:Float, samples:Int) {
        this.scale = scale;
        this.bias = bias;
        this.samples = samples;
        this.shader = new Shader("parallax_occlusion_mapping");
    }

    public function apply(material:Material, object:Object3D) {
        shader.bind();
        shader.setUniform1f("scale", scale);
        shader.setUniform1f("bias", bias);
        shader.setUniform1i("samples", samples);
        material.apply();
        object.draw();
    }
}

// StandardMaterial.hx
package armory.graphics.shaders;

import armory.graphics.GL;
import armory.graphics.Shader;

class StandardMaterial {
    // ...

    public var parallaxOcclusionMapping:ParallaxOcclusionMapping;

    public function new() {
        // ...
        parallaxOcclusionMapping = new ParallaxOcclusionMapping(0.01, 0.01, 10);
    }

    public function apply(object:Object3D) {
        // ...
        if (parallaxOcclusionMapping != null) {
            parallaxOcclusionMapping.apply(this, object);
        }
    }
}

// MaterialNode.hx
package armory.graphics;

import armory.graphics.Material;
import armory.graphics.Shader;

class MaterialNode {
    // ...

    public var parallaxOcclusionMapping:Bool;

    public function new() {
        // ...
        parallaxOcclusionMapping = false;
    }

    public function apply(material:Material) {
        // ...
        if (parallaxOcclusionMapping) {
            material.parallaxOcclusionMapping = new ParallaxOcclusionMapping(0.01, 0.01, 10);
        }
    }
}

// ObjectMaterialProperties.hx
package armory.graphics;

import armory.graphics.Material;
import armory.graphics.Shader;

class ObjectMaterialProperties {
    // ...

    public var parallaxOcclusionMapping:Bool;

    public function new() {
        // ...
        parallaxOcclusionMapping = false;
    }

    public function apply(material:Material) {
        // ...
        if (parallaxOcclusionMapping) {
            material.parallaxOcclusionMapping = new ParallaxOcclusionMapping(0.01, 0.01, 10);
        }
    }
}